# Generated by Django 5.2.5 on 2025-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('moderation_status', models.CharField(choices=[('unclassified', 'Unclassified'), ('neutral', 'Neutral'), ('toxic', 'Toxic'), ('review', 'Review'), ('deleted', 'Deleted')], default='unclassified', max_length=20)),
            ],
        ),
    ]
